name: Deploy PHP Project

on:
    push:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code and checkout
        uses: actions/checkout@v4
      
      - name: PHP Configuration
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Server Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/phpmyadmin/test-deploy
            ls -ls