name: Deploy PHP Project

on:
    push:
      branches:
        - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get code and checkout
        uses: actions/checkout@v4
      
      - name: PHP Configuration
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Server Deploy
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html/phpmyadmin
            ls -ls
            if [ -d "design-patterns" ]; then
              echo "📦 The folder exists. Updating the project..."
              cd patterns-design
              git reset --hard
              git pull origin main
            else
              echo "🆕 The folder does not exist. Cloning the project..."
              git clone https://github.com/CamiloSerrano95/design-patterns.git
              cd patterns-design
              ls -ls
            fi

